package Desafio;

public class ScriptMySQL {
	
	/*	ESSE SCRIPT É PARA CRIAR A TABELA E A TRIGGER USADA PARA PEGAR A DATA E HORA NA INSERÇÃO DOS DADOS
	 * 
	 * TABELA:
	 * 
	CREATE TABLE USUARIO (
	ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(80) NOT NULL,
    LOGIN VARCHAR(50) NOT NULL,
    SENHA VARCHAR(30) NOT NULL,
    DT_CAD VARCHAR(30))
	 * 
	 * 
	 * 
	 * 
	 * TRIGGER:
	 * 
	DELIMITER $
	CREATE TRIGGER DataDoCadastro BEFORE INSERT
	ON USUARIO
	FOR EACH ROW
	BEGIN
		SET NEW.DT_CAD = sysdate();
	END$
	DELIMITER ;
	 * 
	 * 
	 * 
	 * 
	 */

}
